#ifndef ARMSIM_ARM6_SIM_CONFIG_H_
#define ARMSIM_ARM6_SIM_CONFIG_H_

#include "arm_core/arm_types.h"

#define ARMSIM_ARM6_TORQUE_LIMITS_NM \
  { ARM_REAL(10.0), ARM_REAL(40.0), ARM_REAL(30.0), ARM_REAL(8.0), ARM_REAL(8.0), ARM_REAL(8.0) }

#define ARMSIM_ARM6_PVI_PARAMS \
  { \
    { ARM_REAL(25.0), ARM_REAL(4.0), ARM_REAL_ZERO, ARM_REAL_ZERO, ARM_REAL(10.0) }, \
    { ARM_REAL(120.0), ARM_REAL(18.0), ARM_REAL_ZERO, ARM_REAL_ZERO, ARM_REAL(40.0) }, \
    { ARM_REAL(80.0), ARM_REAL(14.0), ARM_REAL_ZERO, ARM_REAL_ZERO, ARM_REAL(30.0) }, \
    { ARM_REAL(8.0), ARM_REAL(1.2), ARM_REAL_ZERO, ARM_REAL_ZERO, ARM_REAL(8.0) }, \
    { ARM_REAL(8.0), ARM_REAL(1.2), ARM_REAL_ZERO, ARM_REAL_ZERO, ARM_REAL(8.0) }, \
    { ARM_REAL(4.0), ARM_REAL(0.8), ARM_REAL_ZERO, ARM_REAL_ZERO, ARM_REAL(8.0) } \
  }

#define ARMSIM_ARM6_DQ_LIMITS_RAD_S \
  { ARM_REAL(1.8), ARM_REAL(1.2), ARM_REAL(1.4), ARM_REAL(2.5), ARM_REAL(2.5), ARM_REAL(3.0) }

#define ARMSIM_ARM6_DDQ_LIMITS_RAD_S2 \
  { ARM_REAL(6.0), ARM_REAL(4.0), ARM_REAL(5.0), ARM_REAL(12.0), ARM_REAL(12.0), ARM_REAL(16.0) }

#define ARMSIM_ARM6_STATE_FILTER_PARAMS \
  { \
    { ARM_REAL_ZERO, ARM_REAL(0.006), false }, \
    { ARM_REAL_ZERO, ARM_REAL(0.006), false }, \
    { ARM_REAL_ZERO, ARM_REAL(0.006), false }, \
    { ARM_REAL_ZERO, ARM_REAL(0.004), false }, \
    { ARM_REAL_ZERO, ARM_REAL(0.004), false }, \
    { ARM_REAL_ZERO, ARM_REAL(0.004), false } \
  }

#define ARMSIM_ARM6_SAFETY_Q_MARGIN_RAD ARM_REAL(0.04)
#define ARMSIM_ARM6_SAFETY_DQ_LIMIT_SCALE ARM_REAL(1.5)

#define ARMSIM_HARSH_CONTROL_PERIOD_S ARM_REAL(0.002)
#define ARMSIM_HARSH_CONTROL_JITTER_S ARM_REAL(0.00025)
#define ARMSIM_HARSH_SENSOR_DELAY_STEPS 2u
#define ARMSIM_HARSH_ENCODER_RESOLUTION_RAD ARM_REAL(0.001)
#define ARMSIM_HARSH_Q_NOISE_RAD ARM_REAL(0.00035)
#define ARMSIM_HARSH_DQ_NOISE_RAD_S ARM_REAL(0.05)
#define ARMSIM_HARSH_TAU_EST_NOISE_NM ARM_REAL(0.08)
#define ARMSIM_HARSH_DQ_FILTER_ALPHA ARM_REAL_ONE
#define ARMSIM_HARSH_ACTUATOR_TAU_TIME_CONSTANT_S ARM_REAL(0.006)
#define ARMSIM_HARSH_ACTUATOR_TAU_RATE_LIMIT_NM_S ARM_REAL(450.0)
#define ARMSIM_HARSH_ACTUATOR_DEADBAND_NM ARM_REAL(0.04)
#define ARMSIM_HARSH_RANDOM_SEED 0x12345678u

#endif
