/* Generated from configs/arm6_placeholder.yaml. Do not edit by hand. */
#ifndef ARMSIM_ARM6_SIM_CONFIG_H_
#define ARMSIM_ARM6_SIM_CONFIG_H_

#include "arm_core/joint_gravity_ff.h"
#include "arm_motion/joint_kinematics.h"
#include "arm_common/arm_types.h"

#define ARMSIM_ARM6_TORQUE_LIMITS_NM \
  { ARM_REAL(10), ARM_REAL(40), ARM_REAL(30), ARM_REAL(8), ARM_REAL(8), ARM_REAL(8) }

#define ARMSIM_ARM6_PD_PARAMS \
  { \
    { ARM_REAL(18), ARM_REAL(2.5), ARM_REAL(4) }, \
    { ARM_REAL(48), ARM_REAL(11), ARM_REAL(11) }, \
    { ARM_REAL(38), ARM_REAL(8.5), ARM_REAL(9.5) }, \
    { ARM_REAL(6), ARM_REAL(0.8), ARM_REAL(3) }, \
    { ARM_REAL(18), ARM_REAL(2.4), ARM_REAL(6) }, \
    { ARM_REAL(3), ARM_REAL(0.5), ARM_REAL(2) } \
  }

#define ARMSIM_ARM6_DQ_LIMITS_RAD_S \
  { ARM_REAL(0.75), ARM_REAL(0.5), ARM_REAL(0.7), ARM_REAL(2), ARM_REAL(3), ARM_REAL(3.8) }

#define ARMSIM_ARM6_DDQ_LIMITS_RAD_S2 \
  { ARM_REAL(2), ARM_REAL(1.2), ARM_REAL(1.8), ARM_REAL(10), ARM_REAL(16), ARM_REAL(22) }

#define ARMSIM_ARM6_DDDQ_LIMITS_RAD_S3 \
  { ARM_REAL(2.5), ARM_REAL(1.5), ARM_REAL(2), ARM_REAL(60), ARM_REAL(90), ARM_REAL(130) }

#define ARMSIM_ARM6_STATE_FILTER_PARAMS \
  { \
    { ARM_REAL_ZERO, ARM_REAL(0.012), false }, \
    { ARM_REAL_ZERO, ARM_REAL(0.026), false }, \
    { ARM_REAL_ZERO, ARM_REAL(0.024), false }, \
    { ARM_REAL_ZERO, ARM_REAL(0.01), false }, \
    { ARM_REAL_ZERO, ARM_REAL(0.01), false }, \
    { ARM_REAL_ZERO, ARM_REAL(0.01), false } \
  }

#define ARMSIM_ARM6_GRAVITY_FF_PARAMS \
  { \
    ARM_DEFAULT_DOF, \
    7u, \
    { ARM_REAL_ZERO, ARM_REAL_ZERO, ARM_REAL(-9.81) }, \
    { \
    { JOINT_GRAVITY_FF_NO_BODY, JOINT_GRAVITY_FF_NO_JOINT, { ARM_REAL_ZERO, ARM_REAL_ZERO, ARM_REAL_ZERO }, { ARM_REAL_ZERO, ARM_REAL_ZERO, ARM_REAL_ZERO }, ARM_REAL(1.6), { ARM_REAL_ZERO, ARM_REAL_ZERO, ARM_REAL_ZERO } }, \
    { 0, 0, { ARM_REAL_ZERO, ARM_REAL_ZERO, ARM_REAL(0.04) }, { ARM_REAL_ZERO, ARM_REAL_ZERO, ARM_REAL_ONE }, ARM_REAL(2), { ARM_REAL_ZERO, ARM_REAL_ZERO, ARM_REAL(0.126) } }, \
    { 1, 1, { ARM_REAL_ZERO, ARM_REAL_ZERO, ARM_REAL(0.18) }, { ARM_REAL_ZERO, ARM_REAL_ONE, ARM_REAL_ZERO }, ARM_REAL(3.55), { ARM_REAL(0.15323943662), ARM_REAL_ZERO, ARM_REAL_ZERO } }, \
    { 2, 2, { ARM_REAL(0.34), ARM_REAL_ZERO, ARM_REAL_ZERO }, { ARM_REAL_ZERO, ARM_REAL_ONE, ARM_REAL_ZERO }, ARM_REAL(3.2), { ARM_REAL(0.105), ARM_REAL_ZERO, ARM_REAL_ZERO } }, \
    { 3, 3, { ARM_REAL(0.28), ARM_REAL_ZERO, ARM_REAL_ZERO }, { ARM_REAL_ONE, ARM_REAL_ZERO, ARM_REAL_ZERO }, ARM_REAL(0.35), { ARM_REAL(0.0375), ARM_REAL_ZERO, ARM_REAL_ZERO } }, \
    { 4, 4, { ARM_REAL(0.075), ARM_REAL_ZERO, ARM_REAL_ZERO }, { ARM_REAL_ZERO, ARM_REAL_ONE, ARM_REAL_ZERO }, ARM_REAL(0.59), { ARM_REAL(0.0121186440678), ARM_REAL_ZERO, ARM_REAL_ZERO } }, \
    { 5, 5, { ARM_REAL(0.065), ARM_REAL_ZERO, ARM_REAL_ZERO }, { ARM_REAL_ONE, ARM_REAL_ZERO, ARM_REAL_ZERO }, ARM_REAL(0.64), { ARM_REAL(0.081953125), ARM_REAL_ZERO, ARM_REAL_ZERO } } \
    } \
  }

#define ARMSIM_ARM6_KINEMATICS_PARAMS \
  { \
    ARM_DEFAULT_DOF, \
    7u, \
    6, \
    { ARM_REAL(0.19), ARM_REAL_ZERO, ARM_REAL_ZERO }, \
    { \
    { JOINT_KINEMATICS_NO_BODY, JOINT_KINEMATICS_NO_JOINT, { ARM_REAL_ZERO, ARM_REAL_ZERO, ARM_REAL_ZERO }, { ARM_REAL_ZERO, ARM_REAL_ZERO, ARM_REAL_ZERO }, ARM_REAL_ZERO, ARM_REAL_ZERO }, \
    { 0, 0, { ARM_REAL_ZERO, ARM_REAL_ZERO, ARM_REAL(0.04) }, { ARM_REAL_ZERO, ARM_REAL_ZERO, ARM_REAL_ONE }, ARM_REAL(-3.14159), ARM_REAL(3.14159) }, \
    { 1, 1, { ARM_REAL_ZERO, ARM_REAL_ZERO, ARM_REAL(0.18) }, { ARM_REAL_ZERO, ARM_REAL_ONE, ARM_REAL_ZERO }, ARM_REAL(-2.6), ARM_REAL(2.6) }, \
    { 2, 2, { ARM_REAL(0.34), ARM_REAL_ZERO, ARM_REAL_ZERO }, { ARM_REAL_ZERO, ARM_REAL_ONE, ARM_REAL_ZERO }, ARM_REAL(-2.8), ARM_REAL(2.8) }, \
    { 3, 3, { ARM_REAL(0.28), ARM_REAL_ZERO, ARM_REAL_ZERO }, { ARM_REAL_ONE, ARM_REAL_ZERO, ARM_REAL_ZERO }, ARM_REAL(-3.14159), ARM_REAL(3.14159) }, \
    { 4, 4, { ARM_REAL(0.075), ARM_REAL_ZERO, ARM_REAL_ZERO }, { ARM_REAL_ZERO, ARM_REAL_ONE, ARM_REAL_ZERO }, ARM_REAL(-3.14159), ARM_REAL(3.14159) }, \
    { 5, 5, { ARM_REAL(0.065), ARM_REAL_ZERO, ARM_REAL_ZERO }, { ARM_REAL_ONE, ARM_REAL_ZERO, ARM_REAL_ZERO }, ARM_REAL(-3.14159), ARM_REAL(3.14159) } \
    } \
  }

#define ARMSIM_ARM6_SAFETY_Q_MARGIN_RAD ARM_REAL(0.04)
#define ARMSIM_ARM6_SAFETY_DQ_LIMIT_SCALE ARM_REAL(1.5)

#define ARMSIM_HARSH_CONTROL_PERIOD_S ARM_REAL(0.002)
#define ARMSIM_HARSH_CONTROL_JITTER_S ARM_REAL(0.00025)
#define ARMSIM_HARSH_SENSOR_DELAY_STEPS 2u
#define ARMSIM_HARSH_ENCODER_RESOLUTION_RAD ARM_REAL(0.001)
#define ARMSIM_HARSH_Q_NOISE_RAD ARM_REAL(0.00035)
#define ARMSIM_HARSH_DQ_NOISE_RAD_S ARM_REAL(0.05)
#define ARMSIM_HARSH_TAU_EST_NOISE_NM ARM_REAL(0.08)
#define ARMSIM_HARSH_DQ_FILTER_ALPHA ARM_REAL_ONE
#define ARMSIM_HARSH_ACTUATOR_TAU_TIME_CONSTANT_S ARM_REAL(0.006)
#define ARMSIM_HARSH_ACTUATOR_TAU_RATE_LIMIT_NM_S ARM_REAL(450)
#define ARMSIM_HARSH_ACTUATOR_DEADBAND_NM ARM_REAL(0.04)
#define ARMSIM_HARSH_RANDOM_SEED 0x12345678u

#endif
